// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GsLPKdSD0NIR1T1wN88hCdrar-mHUPQ',
    appId: '1:925195634225:web:da295ae07bfb25c7a0f710',
    messagingSenderId: '925195634225',
    projectId: 'movie-app-eaa20',
    authDomain: 'movie-app-eaa20.firebaseapp.com',
    storageBucket: 'movie-app-eaa20.appspot.com',
    measurementId: 'G-R74RKY66W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPJ3jckTDyJAH5STqkKdW0DP-cWn49pU',
    appId: '1:925195634225:android:bb21a713b4a95797a0f710',
    messagingSenderId: '925195634225',
    projectId: 'movie-app-eaa20',
    storageBucket: 'movie-app-eaa20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuID6Pc888R0EuxOQnI9w4bU8ox7AT7I',
    appId: '1:925195634225:ios:2bf23b4b478f97dfa0f710',
    messagingSenderId: '925195634225',
    projectId: 'movie-app-eaa20',
    storageBucket: 'movie-app-eaa20.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuID6Pc888R0EuxOQnI9w4bU8ox7AT7I',
    appId: '1:925195634225:ios:2bf23b4b478f97dfa0f710',
    messagingSenderId: '925195634225',
    projectId: 'movie-app-eaa20',
    storageBucket: 'movie-app-eaa20.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9GsLPKdSD0NIR1T1wN88hCdrar-mHUPQ',
    appId: '1:925195634225:web:fa766f3482a0c8e6a0f710',
    messagingSenderId: '925195634225',
    projectId: 'movie-app-eaa20',
    authDomain: 'movie-app-eaa20.firebaseapp.com',
    storageBucket: 'movie-app-eaa20.appspot.com',
    measurementId: 'G-T8D6P5JPZN',
  );
}
